#!/bin/bash
#install dependencies

##installing apache
sudo apt update
sudo apt install apache2 -y

##install mysql 
sudo apt install mysql-server -y

##installing php
sudo apt install php libapache2-mod-php php-mysql -y
##configure wordpress user database
echo "enter wordpress_database"= "$wpdb"
read wpdb
echo "enter wordpress_user name"=""$wpuser
read wpuser
echo "enter password for user"="$password"
read password

sudo mysql <<EOF
CREATE DATABASE $wpdb DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
CREATE USER '$wpuser'@'%' IDENTIFIED WITH mysql_native_password BY '$password';
GRANT ALL PRIVILEGES ON $wpdb.* TO '$wpuser'@'%';
FLUSH PRIVILEGES;
exit;
EOF

##installing additional php extensions---
sudo apt install php-curl php-gd php-mbstring php-xml php-xmlrpc php-soap php-intl php-zip -y
cat > /etc/apache2/sites-available/wordpress.conf <<EOF
<VirtualHost *:80>
    DocumentRoot /var/www/html/wordpress
    <Directory /var/www/html/wordpress/>
        AllowOverride All
    </Directory>
</VirtualHost>
EOF
sudo apache2ctl configtest
sudo systemctl reload apache2
sudo a2enmod rewrite
sudo a2ensite wordpress.conf

#installing wordpress

cd /tmp
curl -O https://wordpress.org/latest.tar.gz
tar xzvf latest.tar.gz
touch /tmp/wordpress/.htaccess
sudo cp /tmp/wordpress/wp-config-sample.php /tmp/wordpress/wp-config.php
sudo mkdir /tmp/wordpress/wp-content/upgrade
sudo cp -a /tmp/wordpress/. /var/www/html/wordpress

#setting wordpress config file

wpsecure_key= $(curl -s https://api.wordpress.org/secret-key/1.1/salt/)


sudo cat > /var/www/html/wordpress/wp-config.php <<EOF
<?php
/** The name of the database for WordPress */
define( 'DB_NAME', '${wpdb}' );

/** MySQL database username */
define( 'DB_USER', '${wpuser}' );

/** MySQL database password */
define( 'DB_PASSWORD', '${password}' );

/** MySQL hostname */
define( 'DB_HOST', 'localhost' );

/** Database charset to use in creating database tables. */
define( 'DB_CHARSET', 'utf8' );

/** The database collate type. Don't change this if in doubt. */
define( 'DB_COLLATE', '' );

${wpsecure_key}
$table_prefix = 'wp_';
define( 'WP_DEBUG', false );
if ( ! defined( 'ABSPATH' ) ) {
        define( 'ABSPATH', __DIR__ . '/' );
}
require_once ABSPATH . 'wp-settings.php';
EOF
sudo chown -R www-data:www-data /var/www/html/wordpress
sudo find /var/www/html/wordpress/ -type d -exec chmod 770 {} \;
sudo find /var/www/html/wordpress/ -type f -exec chmod 664 {} \;



