apiVersion: v1
kind: Service
metadata:
  name: wordpress
  
spec:
  type: NodePort
  selector:
    app: wordpress
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30081

---
apiVersion: v1
kind: Pod
metadata:
  name: wpod
  labels:
    app: wordpress
spec:
  containers:
  - name: wordpress
    image: ubuntu
    volumeMounts:
    - name: wordpress-volume
      mountPath: /script
    command: ["/script/wordpress.sh"]
  volumes: 
  - name: wordpress-volume
    configMap:
      name: create-wordpress.sh
      defaultMode: 0744    
